# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'stARM' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for stARM

  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Database', '~> 5.11.0'
  target 'stARMTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
